services:
  - type: web
    name: church-cell-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements-prod.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
